a=int(input("enter value of a="))
b=int(input("enter value of b="))
print("="*50)
print("{}+{}={}".format(a,b,a+b))
print("="*50)
print("{}-{}={}".format(a,b,a-b))
print("="*50)
print("{}*{}={}".format(a,b,a*b))
print("="*50)
print("{}/{}={}".format(a,b,a/b))
print("="*50)
print("{}//{}={}".format(a,b,a//b))
print("="*50)
print("{}%{}={}".format(a,b,a%b))
print("="*50) *
print("{}**{}={}".format(a,b,a**b))
print("="*50)